"""Browse faces that the C++ rivet injector can use for Boolean fusion."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


def load_shape(step_path: Path):
    from OCC.Core.STEPControl import STEPControl_Reader

    reader = STEPControl_Reader()
    if reader.ReadFile(str(step_path)) != 1:
        raise RuntimeError(f"Unable to read STEP file: {step_path}")
    reader.TransferRoots()
    return reader.OneShape()


def face_center(face):
    from OCC.Core.BRepBndLib import brepbndlib
    from OCC.Core.Bnd import Bnd_Box
    from OCC.Core.gp import gp_Pnt

    box = Bnd_Box()
    brepbndlib.Add(face, box)
    x_min, y_min, z_min, x_max, y_max, z_max = box.Get()
    return gp_Pnt((x_min + x_max) * 0.5, (y_min + y_max) * 0.5, (z_min + z_max) * 0.5)


def model_center_and_diagonal(shape):
    from OCC.Core.BRepBndLib import brepbndlib
    from OCC.Core.Bnd import Bnd_Box
    from OCC.Core.gp import gp_Pnt

    box = Bnd_Box()
    brepbndlib.Add(shape, box)
    x_min, y_min, z_min, x_max, y_max, z_max = box.Get()
    center = gp_Pnt((x_min + x_max) * 0.5, (y_min + y_max) * 0.5, (z_min + z_max) * 0.5)
    diagonal = ((x_max - x_min) ** 2 + (y_max - y_min) ** 2 + (z_max - z_min) ** 2) ** 0.5
    return center, max(diagonal, 1.0)


def face_map(shape):
    from OCC.Core.TopAbs import TopAbs_FACE
    from OCC.Core.TopExp import topexp
    from OCC.Core.TopTools import TopTools_IndexedMapOfShape

    mapped_faces = TopTools_IndexedMapOfShape()
    topexp.MapShapes(shape, TopAbs_FACE, mapped_faces)
    return mapped_faces


def read_candidates(csv_path: Path, mapped_faces, max_candidates: int):
    candidates = []
    with csv_path.open(newline="", encoding="utf-8") as input_file:
        for row in csv.DictReader(input_file):
            face_id = int(row["face_id"])
            if face_id <= 0 or face_id > mapped_faces.Size():
                continue
            candidates.append((
                face_id,
                mapped_faces.FindKey(face_id),
                int(row["solid_index"]),
                float(row["area"]),
                int(row["surface_type"]),
            ))
    candidates.sort(key=lambda item: item[3], reverse=True)
    return candidates[:max_candidates]


def display_candidates(shape, candidates) -> None:
    from OCC.Core.Quantity import Quantity_NOC_GRAY, Quantity_NOC_ORANGE
    from OCC.Core.TopoDS import topods
    from OCC.Core.gp import gp_Dir, gp_Vec
    from OCC.Display.SimpleGui import init_display

    display, start_display, add_menu, add_function_to_menu = init_display(size=(1440, 960))
    model_center, diagonal = model_center_and_diagonal(shape)
    current_index = 0

    def show_current_candidate() -> None:
        face_id, raw_face, solid_index, area, surface_type = candidates[current_index]
        face = topods.Face(raw_face)
        display.EraseAll()
        display.DisplayShape(shape, color=Quantity_NOC_GRAY, transparency=0.0, update=False)
        display.DisplayShape(face, color=Quantity_NOC_ORANGE, update=False)
        center = face_center(face)
        offset = gp_Vec(model_center, center)
        if offset.SquareMagnitude() < 1.0e-12:
            offset = gp_Vec(0.0, 0.0, 1.0)
        label_point = center.Translated(gp_Vec(gp_Dir(offset)) * (diagonal * 0.075))
        display.DisplayMessage(
            label_point,
            f"F{face_id}  ({current_index + 1}/{len(candidates)})",
            height=28.0,
            message_color=(0.0, 0.0, 0.0),
            update=False,
        )
        display.Repaint()
        print(f"Showing F{face_id}: solid={solid_index}, surface={surface_type}, area={area:.3f}")

    def previous_candidate() -> None:
        nonlocal current_index
        current_index = (current_index - 1) % len(candidates)
        show_current_candidate()

    def next_candidate() -> None:
        nonlocal current_index
        current_index = (current_index + 1) % len(candidates)
        show_current_candidate()

    add_menu("Candidate")
    add_function_to_menu("Candidate", previous_candidate)
    add_function_to_menu("Candidate", next_candidate)
    show_current_candidate()
    display.FitAll()
    print("Use Candidate > previous/next candidate to browse.")
    print("Tell Codex one or more displayed F-numbers to use as rivet host faces.")
    start_display()


def parse_args():
    parser = argparse.ArgumentParser(description="Browse Boolean-fusable rivet host faces.")
    parser.add_argument("step_model", type=Path, help="Source STEP model used by Detector.exe.")
    parser.add_argument("--candidate-csv", type=Path, help="CSV generated by --dump-boolean-host-faces.")
    parser.add_argument(
        "--max-candidates",
        type=int,
        default=20,
        help="Display only the largest eligible faces (default: 20).",
    )
    parser.add_argument("--no-display", action="store_true", help="Validate the candidate CSV without opening a GUI.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.max_candidates <= 0:
        raise ValueError("--max-candidates must be positive")
    candidate_csv = args.candidate_csv or args.step_model.with_suffix(".boolean_host_faces.csv")
    if not candidate_csv.is_file():
        raise FileNotFoundError(
            f"Candidate CSV not found: {candidate_csv}. Run Detector.exe --dump-boolean-host-faces first."
        )
    shape = load_shape(args.step_model)
    candidates = read_candidates(candidate_csv, face_map(shape), args.max_candidates)
    if not candidates:
        raise RuntimeError("No Boolean-fusable faces from the candidate CSV could be mapped to this STEP file.")
    print(f"Boolean-fusable faces shown: {len(candidates)} (largest by area)")
    print(f"Candidate CSV: {candidate_csv}")
    if not args.no_display:
        display_candidates(shape, candidates)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
